// lang-es.ts

export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'Payment method': 'Mode de paiement',
    'Your password must have at least 6 characters': 'Votre mot de passe doit contenir au moins 6 caractères',
    'Your quotes at you clients place': 'Vos devis chez vos clients !',
    'Forgotten password?': 'Mot de passe oublié ?',
    'Back': 'Retour',
    'Month': 'Mois',
    'Year': 'Année',
    'Create new Intervention': 'Nouvelle intervention',
    'Password': 'Mot de passe',
    'Outstanding balance': 'Reste à payer',
    'Add': 'Ajouter',
    'Meeting': 'Rendez-voous',
    'Register': 'S\'enregistrer',
    'Dashboard': 'Tableau de Bord',
    'My Planning': 'Mon Calendrier',
    'Planning': 'Calendrier',
    'My profile': 'Mon profil',
    'My company': 'Mon Entreprise',
    'Logout': 'Déconnexion',
    'Items per page': 'Eléments par page',
    'Accountancy': 'Comptabilité',
    'Payments': 'Paiements',
    'Payment': 'Paiement',
    'Expenses': 'Dépenses',
    'Expense': 'Dépense',
    'Reporting': 'Statistiques',
    'Settings': 'Paramètres',
    'Product': 'Produit',
    'Invoice': 'Facture',
    'Send document to client': 'Envoyer le document par mail',
    'Home': 'Accueil',
    'Edit': 'Modifier',
    'WorkingAddress': 'Réference Chantier',
    'Painfulness': 'Pénibilité',
    'VAT': 'TVA',
    'Number Id': 'Numéro',
    'Appointment': 'Rendez-vous',
    'Length': 'Longeur',
    'Edit Quote': 'Edition du devis',
    'Total with taxes': 'Total TTC',

    'Add a product': 'Ajouter un produit',
    'Create a new': 'Créer un nouveau',
    'product': 'produit',
    'Products': 'Produits',
    'Create an new product': 'Créer un nouveau produit',
    'List': 'Liste',
    'Price': 'Prix',
    'Name': 'Nom',
    'Price without taxes': 'Prix HT',
    'Product Name': 'Nom du Produit',
    'companie': 'Entreprise',
    'Height': 'Hauteur',
    'Width': 'Largeur',
    'Depth': 'Profondeur',
    'CostPrice': 'Coût',
    'Selling Price': 'Prix de vente',
    'Save': 'Sauvegarder',
    'Delete': 'Supprimer',
    'Project': 'Rendez-vous',
    'Enter your password to approve changes': 'Renseigner votre mot de passe pour valider les changements',
    'Intervention Settings': 'Paramètres d\'intervention',
    'Legal Notice': 'Notes legales',
    'Save & Create project': 'Sauvegarder et Créer Rendez-vous',
    'Issue date': 'Date d\'émission',
    'Expiry date': 'Date d\'expiration',
    'Users': 'Contacts',
    'User': 'Contact',
    'Team': 'Équipe',
    'External Contact': 'Contact Externe',
    'Create a new team member': 'Créer un nouveau membre interne',
    'Create a new external member': 'Créer un nouveau contact externe',
    'Title': 'Titre',
    'Firstname': 'Prénom',
    'Lastname': 'Nom',
    'Type User': 'Fonction',
    'Phone Number': 'Téléphone',
    'Address': 'Adresse',
    'additional address': 'Complément Adresse',
    'city': 'Ville',
    'City': 'Ville',
    'state': 'Pays',
    'State': 'Etat',
    'zip': 'Code Postal',
    'Zip': 'Code Postal',
    'Country': 'Pays',
    'Acces Code': 'Code Entrée',
    'accessCode': 'Code Immeuble',
    'Acces type': 'Type d´accès',
    'floor': 'Etage',
    'Floor': 'Etage',
    'Number': 'N°',
    'Other': 'Autre',
    'Identity': 'Détails',
    'Details': 'Détails',
    'Calendar Color': 'Couleur du calendrier',
    'Surface': 'Surface',
    'Phone': 'Téléphone',
    'Add Picture': 'Ajouter image',
    'New Address': 'Nouvelle Adresse',
    'Mr.': 'M.',
    'Mrs.': 'Mme',
    'Address shipping': 'Adresse Intervention',
    'Address billing': 'Adresse de Facturation',
    'Additional address': 'Complément adresse',
    'New contact person': 'Nouvel interlocuteur',
    'Contact person': 'Interlocuteur',
    'Company': 'Entreprise',
    'Companies': 'Fournisseurs',
    'Billing': 'Facturation',
    'Shipping': 'Intervention',
    'Contact type': 'Fonction',
    'New Contact person': 'Nouvel Interlocuteur',
    'Phone number': 'Téléphone',
    'Status': 'Statut',
    'Details Quote': 'Détails',



    'Items': 'Eléments',



    'Quotes': 'Devis',
    'Paid': 'Payé',
    'quote': 'devis',
    'Create a new quote': 'Créer un nouveau Devis',
    'Assigned to me': 'Assigné à Moi',
    'Assigned to': 'Assigné à',
    'Owner': 'Propriétaire',
    'Download PDF': 'Télécharger PDF',
    'Customer': 'Client',
    'Customers': 'Clients',
    'Supplier': 'Fournisseur',
    'Suppliers': 'Fournisseurs',
    'Estimate Number': 'Numéro du devis',
    'Issue Date': 'Date',
    'Expiry Date': 'Date de Validité',
    'Currency': 'Devise',
    'Estimate Template': 'Modèle de Devis',
    'Amounts are': 'Les montants sont',
    'Discount': 'Remise',
    'Subject': 'Sujet',
    'Add Row': 'Ajouter Ligne',
    'Item': 'Objet',
    'Quantity': 'Quantité',
    'nameTemplate': 'Nom du modèle',
    'templateQuote': 'Recherche',
    'Save TemplateQuote': 'Sauvegarder le Modèle',
    'Add new one': 'Ajouter',
    'Create a new Paiement': 'Nouveau Paiement',
    'Please Select': 'Mode de Paiement',
    'Amount': 'Montant',
    'Quote edit date': 'Date Édition',
    'Quote validity date': 'Date de Validité',
    'Quote title': 'Titre du devis',
    'Template': 'Modèle',
    'Price excl tax': 'Prix HT',
    'VAT (%)': 'TVA (%)',
    'Total excl tax': 'Total HT',
    'Category': 'Catégorie',
    'Text': 'Texte',
    'priceWithoutTaxes': 'Prix HT',
    'Reset': 'Recommencer',
    'Unsign': 'Effacer',
    'Quote': 'Devis',
    'Reference Name': 'Nom du Produit',
    'description': 'Description',
    'Unit': 'Unité',
    'Save As Invoice': 'Convertir en Facture',
    'Go to Invoice': 'Consulter Facture',
    'Validate': 'Valider',
    'Show Comments': 'Voir Commentaires',
    'Reference': 'Référence',
    'Paymentquote': 'Encaissement',
    'Sent': 'Envoyée',
    'Date Invoice Paid': 'Date Encaissement',
    'Signed': 'Signé',
    'Rejected': 'Refusé',
    'Signed, pending payment': 'Signé, en attente de règlement',
    'signed': 'Signé',
    'Drawing': 'Dessin',
    'Get invoice': 'Créer Facture',
    'Is Paid': 'Payé',

    'Calendar': 'Calendrier',
    'Start:': 'Débute le :',
    'End:': 'Termine le :',
    'Invoices': 'Factures',
    'invoice': 'Facture',

    'Today': 'Aujourd´hui',


    'project': 'Rendez-vous',
    'Projects': 'Rendez-vous',
    'Ref': 'Référence',
    'Name Project': 'Nom du Rendez-vous',
    'Started': 'En cours',
    'Done': 'Terminé',
    'Assigned To': 'Assigné à',
    'My tasks': 'Mes tâches',
    'Name Task': 'Description tâche',
    'Project sheet': 'Fiche Rendez-vous',


    'task': 'tâche',
    'Tasks': 'Tâches',
    'Add a project': 'Ajouter un projet',
    'Individual' : 'Particulier',

    'Pending Approval': 'Attente de signature',
    'right': 'droit',
    'Rights': 'Droits',



    'today': 'aujourd\'hui',
    'month': 'mois',
    'week': 'semaine',
    'day': 'jour',
    'list': 'liste',



    'Search': 'Recherche',
    'This action is not reversible. Are you sure you want to delete?': 'Cette action est irréversible. Confirmez-vous la suppression ?',

};
